service: app

provider:
    name: aws
    region: us-east-2
    runtime: provided.al2

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            -   httpApi: '*'

package:
    exclude:
        - 'tests/**'
